### ISSUE TITLE
Postgres: issue with "undefined" bindings (0.11.x, bookshelf, regression)

### ISSUE THREAD

**Issue by indeyets** [tgriesser/knex#1646]
We have several bookshelf queries which stopped working after switching to knex 0.11+. Here's one example:

``` js
      const geotag = await Geotag
        .forge()
        .where('url_name', ctx.params.url_name)
        .fetch({ require: true, withRelated: ['country', 'admin1', 'city', 'continent', 'geonames_city'] });
```

And here's the table definition (quite a long one, sorry):

```
libertysoil=# \dS geotags
                                              Table "public.geotags"
       Column        |            Type             |                          Modifiers
---------------------+-----------------------------+--------------------------------------------------------------
 id                  | uuid                        | not null default gen_random_uuid()
 name                | character varying(255)      |
 geonames_country_id | integer                     |
 geonames_city_id    | integer                     |
 url_name            | character varying(255)      |
 type                | character varying(255)      |
 continent_code      | character varying(255)      |
 continent_id        | uuid                        |
 country_id          | uuid                        |
 country_code        | character varying(255)      |
 admin1_code         | character varying(255)      |
 admin1_id           | uuid                        |
 geonames_admin1_id  | integer                     |
 lat                 | real                        |
 lon                 | real                        |
 land_mass           | real                        |
 more                | jsonb                       |
 post_count          | integer                     | default 0
 created_at          | timestamp without time zone | default timezone('utc'::text, now())
 updated_at          | timestamp without time zone | default timezone('utc'::text, now())
 geonames_id         | integer                     |
 _sphinx_id          | bigint                      | not null default nextval('geotags__sphinx_id_seq'::regclass)
Indexes:
    "geotags_pkey" PRIMARY KEY, btree (id)
    "geotags__sphinx_id_index" btree (_sphinx_id)
    "geotags_city_id_index" btree (geonames_city_id)
    "geotags_country_id_index" btree (geonames_country_id)
    "geotags_type_index" btree (type)
    "geotags_url_name_index" btree (url_name)
Foreign-key constraints:
    "geotags_admin1_id_foreign" FOREIGN KEY (admin1_id) REFERENCES geotags(id)
    "geotags_continent_id_foreign" FOREIGN KEY (continent_id) REFERENCES geotags(id)
    "geotags_country_id_foreign" FOREIGN KEY (country_id) REFERENCES geotags(id)
    "geotags_geonames_admin1_id_foreign" FOREIGN KEY (geonames_admin1_id) REFERENCES geonames_admin1(id)
    "geotags_geonames_city_id_foreign" FOREIGN KEY (geonames_city_id) REFERENCES geonames_cities(id) ON UPDATE CASCADE ON DELETE CASCADE
    "geotags_geonames_country_id_foreign" FOREIGN KEY (geonames_country_id) REFERENCES geonames_countries(id) ON UPDATE CASCADE ON DELETE CASCADE
Referenced by:
    TABLE "followed_geotags_users" CONSTRAINT "followed_geotags_users_geotag_id_foreign" FOREIGN KEY (geotag_id) REFERENCES geotags(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE "geotags" CONSTRAINT "geotags_admin1_id_foreign" FOREIGN KEY (admin1_id) REFERENCES geotags(id)
    TABLE "geotags" CONSTRAINT "geotags_continent_id_foreign" FOREIGN KEY (continent_id) REFERENCES geotags(id)
    TABLE "geotags" CONSTRAINT "geotags_country_id_foreign" FOREIGN KEY (country_id) REFERENCES geotags(id)
    TABLE "geotags_posts" CONSTRAINT "geotags_posts_geotag_id_foreign" FOREIGN KEY (geotag_id) REFERENCES geotags(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE "liked_geotags" CONSTRAINT "liked_geotags_geotag_id_foreign" FOREIGN KEY (geotag_id) REFERENCES geotags(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE "posts" CONSTRAINT "posts_liked_geotag_id_foreign" FOREIGN KEY (liked_geotag_id) REFERENCES geotags(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE "schools" CONSTRAINT "schools_country_id_foreign" FOREIGN KEY (country_id) REFERENCES geotags(id) ON UPDATE CASCADE ON DELETE SET NULL
```

the query worked fine with knex 0.10, but 0.11.9 gives us: `{"error":"Undefined binding(s) detected when compiling SELECT query: select \"geotags\".* from \"geotags\" where \"geotags\".\"id\" in (?)"}`.

0.11.1 says `{"error":"select \"geotags\".* from \"geotags\" where \"geotags\".\"id\" in ($1) - Cannot find module 'pg-native'"}`

0.11.2 says something about casting undefined to string

So, overall conclusion is, that later 0.11.x cured some of the symptoms, but there's some underlying issue I can't quite get to.

**Comment by wubzz** [comment]
@indeyets Some information relating to this can be found in #1448 and #1417.

Testing your query without the Bookshelf specific parts using knex 0.10:
```javascript
console.log(knex('geotags').where('url_name', void 0).select().toString());
//select * from "geotags" where "url_name" = DEFAULT
```

Depending on dialect, this would in 0.10 either result in the use of `DEFAULT`, `NULL` or simply a broken query. Knex does not know what to do with undefined bindings, so to prevent bugs in users code, and to solve an otherwise unsolvable issue, we decided to start throwing errors instead, indicating that a query somewhere in your application is not being supplied with what you are in fact trying to supply it with, in this case a *url_name*.

Trying the same in 0.11.10:

```javascript
console.log(knex('geotags').where('url_name', void 0).select().toString());
//Error: Undefined binding(s) detected when compiling SELECT query: select * from "geotags" where "url_name" = ?
```

There's an open issue relating to potentionally adding a stack in this error as well, so that knex can point the user directly to the users own code that is failing.

**Comment by indeyets** [comment]
@wubzz `url_name` is definitely there. first sql-query reaches postgres successfully, followed by the second one (which is by ID, received from the first query).

after that it fails and I suppose that it has something to do with one of relations. some of foreign-key fields are empty and I believe it results in this error.

To put it differently: knex 0.10 gave me equivalent of left-join, and knex 0.11 gives me equivalent of inner-join. (pure speculation, I did not verify this idea properly)

**Comment by wubzz** [comment]
@indeyets Ah my bad, didnt see the query at the bottom. I have no experience with Bookshelf so this is a bit above my head. But the error itself and the reasoning for it stands the same.

@rhys-vdw Do you maybe have an idea on how or why this change affected the example code above?

**Comment by indeyets** [comment]
I just added regression test to our project based on this issue: https://github.com/Lokiedu/libertysoil-site/blob/stable/test/regression/knexTest.js

And here's our bookshelf configuration:
https://github.com/Lokiedu/libertysoil-site/blob/stable/src/api/db/index.js#L469-L516

**Comment by tgriesser** [comment]
@indeyets I'll be taking a closer look at this one soon to see what all might be happening here - thanks for the test cases

**Comment by teckays** [comment]
Just to add a few more details here, I've noticed a `limit` binding being passed to the `where` query even though I did not specify it. So whatever my where clause is, `limit` is appended there and because it doesn't have a value passed in, it's `undefined`

**Comment by ihinsdale** [comment]
+1 for a fix. Experienced the regression upgrading from Knex v0.10.0 to v0.12.6. Using Bookshelf v0.10.3.

**Comment by cmodien** [comment]
Is there a workaround for this?

**Comment by indeyets** [comment]
@tgriesser any news about this one? still fails with `0.12.9`

**Comment by elhigu** [comment]
I don't think this is `knex` issue unless there is test code that can be ran with `knex` without bookshelf. At least this doesn't comply current standards of `knex` bug reports.

**Comment by elhigu** [comment]
Closing as there is no knex reproduction case for this. Sounds like bookshelf is passing undefined bindings somewhere.
