### ISSUE TITLE
Unable to compile Typescript with --esModuleInterop enabled

### ISSUE THREAD

**Issue by jsonmaur** [tgriesser/knex#3210]
# Environment

Knex version: 0.17.0-next3
Node version: 10.15.3
Typescript version: 3.4.5

# Bug

When I try to compile a Typescript app using Knex, the following error occurs with the `--esModuleInterop` [TS compiler option](http://www.typescriptlang.org/docs/handbook/compiler-options.html):

```
node_modules/knex/types/index.d.ts:1328:13 - error TS2430: Interface 'ChainableInterface<T>' incorrectly extends interface 'Bluebird<T>'.
  Types of property 'asCallback' are incompatible.
    Type '(callback: Function) => this' is not assignable to type '{ (callback: (err: any, value?: T | undefined) => void, options?: SpreadOption | undefined): this; (...sink: any[]): this; }'.
      Type 'this' is not assignable to type 'this'. Two different types with this name exist, but they are unrelated.
        Type 'ChainableInterface<T>' is not assignable to type 'this'.

1328   interface ChainableInterface<T = any> extends Bluebird<T> {
```

**Comment by lorefnon** [comment]
@jsonmaur Thanks for reporting this. This has been addressed in https://github.com/tgriesser/knex/pull/3209. In the meanwhile you can consider using version 0.16.5 which should not have this issue.

**Comment by djordje** [comment]
Trying to build my app I realised it builds using `0.17.0-next`, but starting with `0.17.0-next2` it fails with this error.

**Comment by kibertoad** [comment]
Fix released in knex@0.17.0-next4. Please try it out!

**Comment by loxs** [comment]
@kibertoad have in mind that `@latest` is still `next3` so people are hitting it because of this

**Comment by kibertoad** [comment]
Strange, I unpublished it a couple of hours ago. Could you please check if that's still the case?

**Comment by loxs** [comment]
@kibertoad yeah, it still shows as latest in my `yarn info knex` and also here: https://www.npmjs.com/package/knex

**Comment by jsonmaur** [comment]
Thanks for the quick fix! `0.17.0-next4` seems to solve it. But `0.17.0-next3` is still published under the `latest` tag on npm (`next4` is under the `next` tag.)

**Comment by kibertoad** [comment]
Will look into it, thanks. For some reason unpublish didn't work?..

**Comment by kibertoad** [comment]
Looks like second time did the charm, seems gone now. Thank you for bringing it up!
