### ISSUE TITLE
Breaking Change between 0.7.x -> 0.8.x: Inner query with knex.raw()

### ISSUE THREAD

**Issue by hotaru355** [tgriesser/knex#1204]
The following query fails when upgrading knex from version `0.7.3` to `0.8.6`:

```
knex.select(knex.raw('EXISTS(?)', knex.select().from('dual')))

// 0.7.x:   select EXISTS(select * from `dual`)
// 0.8.x:   select EXISTS(?)
```

Is there any way to make this backward compatible? Btw, is there a better way to write this? I have tried below query to no avail (`"TypeError: val.replace is not a function\n    at Object.SqlString.escape (/mnt/jsedvisor/node_modules/knex/lib/query/string.js:39:13)`):

```
knex.select(knex.raw('EXISTS(?)', function() {
  this.select().from('dual')
}))
```

**Comment by rhys-vdw** [comment]
Have you tried a more recent version?

**Comment by elhigu** [comment]
Seem to work with 0.10

```js
knex.select(knex.raw('EXISTS(?)', knex.select().from('dual'))).toString()
Knex:warning - TypeError: Converting circular structure to JSON
'select EXISTS(\'select * from `dual`\')'
```

**Comment by elhigu** [comment]
hmm... actually not, since it is replaced as a string...

**Comment by elhigu** [comment]
Ah, now I remember, the changed raw binding syntax... correct way to do this now a days is:

```js
knex.select(knex.raw('EXISTS(?)', [knex.select().from('dual')])).toString()
'select EXISTS(select * from `dual`)'
```

Between 0.7 and 0.8 `knex.raw` was changed in a way that second parameter for positional bindings must be an array or an object.

**Comment by hotaru355** [comment]
Thanks a lot!
