### ISSUE TITLE
Property 'timeout' does not exist on type 'QueryBuilder'

### ISSUE THREAD

**Issue by 3mini** [tgriesser/knex#3422]
# Environment

Knex version: 0.19.3
Database + version: MySQL 5.7.22
OS: 10.14.6

If issue is about TypeScript definitions, tag @lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
    
    I'm using **Typescript Version 3.5.1**.
    When I upgrade knex version **from 0.17.3 to 0.19.3**, I got a compile error regarding [timeout](http://knexjs.org/#Builder-timeout).
    It worked well before. 🙃

2. Error message
    ```
    Property 'timeout' does not exist on type 'QueryBuilder<unknown, 
    DeferredKeySelection<unknown, never, false, {}, false, {}, never>[]>'
    ```

**Comment by kibertoad** [comment]
It was a bluebird method. We no longer support bluebird.
That said, timeout functionality is, indeed, useful. Wonder if we handle it otherwise right now.

**Comment by Heikkohoo** [comment]
Same issue with the map - property

Property 'map' does not exist on type 'QueryBuilder<unknown, (DeferredKeySelection<unknown, string, true, {}, boolean, {}, unknown> | DeferredKeySelection<unknown, "id", true, {}, false, {}, never>)[]>'

**Comment by elhigu** [comment]
> It was a bluebird method. We no longer support bluebird.
That said, timeout functionality is, indeed, useful. Wonder if we handle it otherwise right now.

IIRC http://knexjs.org/#Builder-timeout is not from bluebird, but actually implemented in knex. It actually cancels the query if timeout is triggered.

**Comment by kibertoad** [comment]
@Heikkohoo `map` is definitely gone for good, just await results and call map on array that you get.
Please check if `timeout` actually works on latest version if you add ts-ignore, if it does, we need to add it to our knex types.

**Comment by Heikkohoo** [comment]
@kibertoad thanks. Got the .map thinghy working.

**Comment by kibertoad** [comment]
@3mini Types were fixed in 0.19.4 that was just published.

**Comment by 3mini** [comment]
@kibertoad Thanks 🙏

**Comment by 3mini** [comment]
@lorefnon There's still a compile error as below.

```
timeout(ms: number, options: {cancel?: boolean}): QueryBuilder<TRecord, TResult>;
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'options' was not provided.
```

According to the [document](http://knexjs.org/#Builder-timeout), the second argument is optional as in the example.

```
knex.select().from('books').timeout(1000)
```

But `options` is not optional argument anymore. 

I think it's better to do this, what do you think?

```
timeout(ms: number, options?: { cancel: boolean }): QueryBuilder<TRecord, TResult>;
```

**Comment by yigaldviri** [comment]
I'm having the same error as in the title.
Migrated to 0.20.0 from 0.15.1
I'm using Bluebird in my project instead of the native Promise (which is overrided by Bluebird) so there's a conflict between my promise's timeout  and Knex's timeout.

```
Interface 'QueryBuilder<TRecord, TResult>' incorrectly extends interface 'ChainableInterface<Resolve<TResult>>'.
  Types of property 'timeout' are incompatible.
    Type '(ms: number, options?: { cancel?: boolean | undefined; } | undefined) => QueryBuilder<TRecord, TResult>' is not assignable to type '(ms: number, message?: string | Error | undefined) => Bluebird<Resolve<TResult>>'.
      Types of parameters 'options' and 'message' are incompatible.
        Type 'string | Error | undefined' is not assignable to type '{ cancel?: boolean | undefined; } | undefined'.
          Type 'string' is not assignable to type '{ cancel?: boolean | undefined; } | undefined'.
```

Is there a way to use Bluebird as my project's Promise and still use Knex?

**Comment by kibertoad** [comment]
@yigaldviri `timeout` method in Knex does not come from Bluebird, it is implemented internally, hence signature is not compatible.
As long as you don't expect Knex to return Bluebird promises to you, you should be able to mix Knex native promises with your in-project Bluebird promises. Probably simplest way to achieve that would be to wrap all knex interactions within `repository` files that would only expose Bluebird promises outside.
That said, if you would ever start using async/await, aren't you going to hit same issue of your promises not being Bluebird promises?

**Comment by kibertoad** [comment]
I wonder if signature will become compatible if we make options an optional argument. I see no reasons why not to. @lorefnon, what do you think?

**Comment by yigaldviri** [comment]
@kibertoad - the thing is that i do "expect Knex to return Bluebird promises to you". I'm using Bluebird instead of native Promises sort of like this: `global.Promise = BluebirdPromise;` and that's why I'm getting this error. Is there any thing I can do to solve this?

Also, I'm using async/await and don't have a problem with Bluebird

**Comment by kibertoad** [comment]
@yigaldviri Right, so that forces all calls to `new Promise` to actually instantiate a Bluebird promise? Other than casting Knex native promises to Bluebird promises, I don't think there is a possible solution for existing version; however, we are definitely going to look into at least addresing the `.timeout` use-case.

**Comment by lorefnon** [comment]
In response to [@3mini's comment](https://github.com/knex/knex/issues/3422#issuecomment-530241087) we had already made the options argument as promise, and it was released in 0.20.0. 

However with 0.20.0 the error reported by @yigaldviri should not be possible (absent external interference with types) because ChainableInterface no longer extends Bluebird so `ChainableInterface#timeout` should not exist. 

@yigaldviri Can you please let us know if any of the following are true: 

1. Do you also have `@types/knex` installed ? 
2. Do you have `@types/bluebird-global` (or something similar) installed, which augments the type of global Promise ?

As @kibertoad mentioned, we have found global promise->bluebird substitution to not be a viable solution because irrespective of what you set `global.Promise` to be, async functions will always return the native one unless you transpile all async/await usage as well which incurs a non-trivial performance hit.

**Comment by yigaldviri** [comment]
Hi @lorefnon ,
1. I'm not using `@types/knex`.
2. I do use  `@types/bluebird-global `

**Comment by kibertoad** [comment]
Released in 0.20.1
