### ISSUE TITLE
knex.ref missing from typescript definitions

### ISSUE THREAD

**Issue by patrickdet** [tgriesser/knex#3026]
# Environment

Knex version: 0.16.3
Database + version: Postgres 10
OS: macOS

# Bug

I am using Knex with typescript and noticed that `knex.ref` is missing from the definition which means I cannot use the following statement from the documenation:

```
knex(knex.ref('Users').withSchema('TenantId'))
  .where(knex.ref('Id'), 1)
  .orWhere(knex.ref('Name'), 'Admin')
  .select(['Id', knex.ref('Name').as('Username')])
```

## Error message

"Property 'ref' does not exist on type 'Knex'".

**Comment by shahnizz** [comment]
+1 @patrickdet Did you ever find a solution for this? Just ran into this same issue

**Comment by kibertoad** [comment]
@shahnizz Workaround is simple - contribute PR with fixed typings :D
See types/knex.d.ts

**Comment by lorefnon** [comment]
This was taken care of in https://github.com/tgriesser/knex/pull/3215.

**Comment by onehorsetown** [comment]
I know Typescript support is "best effort", but the above code fails to compile in Typescript `3.5.1` even with the new `knex.ref` types.

```
knex('foo')
  .where(knex.ref('Id'), 1);  // error TS2345: Argument of type 'Ref<"Id", { Id: "Id"; }>' is not assignable to parameter of type 'string'.
```

`Where<TRecord, TResult>` does accept a single `Raw` parameter, but not a `Raw/Ref` + value.  

As such, I think https://github.com/tgriesser/knex/blob/f3e991d2a45b999898efca074d6c6066f74f7e30/types/index.d.ts#L1021

should be changed to:

```
   (raw: Raw, value: Value | null): QueryBuilder<TRecord, TResult>;
```

typescript version: 3.5.1
knex version: 0.17.5

**Comment by dvishist** [comment]
Did anyone find a solution for this? it is still not compiling for me in typescript `4.9.4`

`Property 'ref' does not exist on type 'typeof knex'.`
